name: "guardian/actions-riff-raff"
description: "Build and upload Riff Raff artifacts."
inputs:
  app:
    description: Riff Raff app name.
    required: true
  config:
    description: Riff Raff configuration (what would normally go in a riff-raff.yaml file). Use `|` to provide a multiline string here. The format should be the same as a normal riff-raff.yaml but with an additional 'sources' list property that can be added to deployments. See the README.md for more info on how this works.
    required: false
  configPath:
    description: Use this to specify the path of a riff-raff.yaml file if you'd rather that than enter the config in your workflow file directly.
    required: false
  projectName:
    description: "Determines Riffraff project name. Use this to override the default `stack::app` naming convention."
    required: false
  dryRun:
    description: If set to true, logs the output but does not upload deployments to the Riff Raff S3 bucket.
    required: false
  buildNumber:
    description: If set, will be used for the build number. (Typically this is read from process.env.GITHUB_RUN_NUMBER.)
    required: false
  stagingDir:
    description: Used to set staging directory. You should not need to set this; it is intended for internal (testing) use only.
    required: false
runs:
  using: "node16"
  main: "index.js"
