name: "guardian/actions-riff-raff"
description: "Build and upload Riff Raff artifacts."
inputs:
  app:
    description: Riff Raff app name. Either this or projectName should be set.
    required: false
  roleArn:
    description: Role to assume using AssumeRoleWithWebIdentity with Github OIDC token to upload files to RiffRaff S3 bucket.
    required: true
  config:
    description: Riff Raff configuration (what would normally go in a riff-raff.yaml file). Use `|` to provide a multiline string here.
    required: false
  configPath:
    description: Use this to specify the path of a riff-raff.yaml file if you'd rather that than enter the config in your workflow file directly.
    required: false
  projectName:
    description: "Determines Riffraff project name. Use this to override the default `stack::app` naming convention."
    required: false
  dryRun:
    description: If set to true, logs the output but does not upload deployments to the Riff Raff S3 bucket.
    required: false
  buildNumber:
    description: If set, will be used for the build number. (Typically this is read from process.env.GITHUB_RUN_NUMBER.)
    required: false
  buildNumberOffset:
    description: If set, will be added to the build number. (e.g. to offset builds to count from builds generated from a previous build tool)
    required: false
  stagingDir:
    description: Used to set staging directory. You should not need to set this; it is intended for internal (testing) use only.
    required: false
  contentDirectories:
    required: true
    description: A list of files/directories to upload to Riff-Raff. An alternative to nesting `sources` inside the `config` input.
  githubToken:
    required: true
    description: A GitHub token scoped to allow pull request commenting.
  commentingStage:
    required: false
    description: When commenting on a pull request, which stage should be used. Typically a pre-production stage.
    default: CODE
  commentingEnabled:
    required: false
    description: Whether to comment on the pull request with Riff-Raff deployment links. See also `commentingStage`.
    default: 'true'
runs:
  using: node20
  main: "dist/index.js"
