name: "guardian/actions-riff-raff"
description: "Build and upload Riff Raff artifacts."
inputs:
  app:
    description: Riff Raff app name. Either this or projectName should be set.
    required: false
  config:
    description: Riff Raff configuration (what would normally go in a riff-raff.yaml file). Use `|` to provide a multiline string here.
    required: false
  configPath:
    description: Use this to specify the path of a riff-raff.yaml file if you'd rather that than enter the config in your workflow file directly.
    required: false
  projectName:
    description: "Determines Riffraff project name. Use this to override the default `stack::app` naming convention."
    required: false
  dryRun:
    description: If set to true, logs the output but does not upload deployments to the Riff Raff S3 bucket.
    required: false
  buildNumber:
    description: If set, will be used for the build number. (Typically this is read from process.env.GITHUB_RUN_NUMBER.)
    required: false
  buildNumberOffset:
    description: If set, will be added to the build number. (e.g. to offset builds to count from builds generated from a previous build tool)
    required: false
  stagingDir:
    description: Used to set staging directory. You should not need to set this; it is intended for internal (testing) use only.
    required: false
  contentDirectories:
    required: true
    description: A list of files/directories to upload to Riff-Raff. An alternative to nesting `sources` inside the `config` input.

# When `actions/runner` supports Node 18 or higher, this could be a Javascript action.
# See https://github.com/guardian/actions-riff-raff/issues/33
runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: Action
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_APP: ${{ inputs.app }}
        INPUT_CONFIG: ${{ inputs.config }}
        INPUT_CONFIGPATH: ${{ inputs.configPath }}
        INPUT_PROJECTNAME: ${{ inputs.projectName }}
        INPUT_DRYRUN: ${{ inputs.dryRun }}
        INPUT_BUILDNUMBER: ${{ inputs.buildNumber }}
        INPUT_BUILDNUMBEROFFSET: ${{ inputs.buildNumberOffset }}
        INPUT_STAGINGDIR: ${{ inputs.stagingDir }}
        INPUT_CONTENTDIRECTORIES: ${{ inputs.contentDirectories }}
