name: test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - run: |
        npm ci
        npm run build

      - uses: ./
        with:
          app: foo
          stack: deployTools
          deployments:
            upload:
              type: aws-s3
              source: test-data
              parameters:
                bucket: aws-some-bucket
                cacheControl: private
                publicReadAcl: false
