name: test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: build
        run: |
          npm ci
          npm run build

      - uses: ./
        with:
          dryRun: true
          app: foo
          stack: deploy
          deployments: |
            upload:
              type: aws-s3
              sources: test-data
              parameters:
                bucket: aws-some-bucket
                cacheControl: private
                publicReadAcl: false
