name: test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: build + test
        run: |
          npm ci
          npm run build
          npm test

      - name: prep action
        run: |
          mkdir my-sources
          touch my-sources/foo.txt

      - uses: ./
        with:
          dryRun: true
          app: foo
          config: |
            stacks:
              - deploy
            regions:
              - eu-west-1
            allowedStages:
              - CODE
              - PROD
            deployments:
              upload:
                type: aws-s3
                sources:
                  - my-sources
                parameters:
                  bucket: aws-some-bucket
                  cacheControl: private
                  publicReadAcl: false
